# Generated by Django 3.1 on 2020-09-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dpi', models.CharField(max_length=12)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('nit', models.IntegerField()),
                ('saldo', models.FloatField()),
                ('limite_credito', models.FloatField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fab', models.CharField(max_length=100)),
                ('existencia_fab', models.IntegerField()),
                ('telefono_fab', models.IntegerField()),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificar', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.FloatField()),
                ('articulos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracion.articulos')),
                ('clientes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracion.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='fabricante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Administracion.fabricantes'),
        ),
    ]
